export const pokemons = [
    {
        id: "UG9rZW1vbjowMDE=",
        number: "001",
        name: "Bulbasaur",
        classification: "Seed Pokémon",
        fleeRate: 0.10,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    },
    {
        id: "UG9rZW1vbjowMDI=",
        number: "002",
        name: "Ivysaur",
        classification: "Seed Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
    },
    {
        id: "UG9rZW1vbjowMDM=",
        number: "003",
        name: "Venusaur",
        classification: "Seed Pokémon",
        fleeRate: 0.05,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
    },
    {
        id: "UG9rZW1vbjowMDQ=",
        number: "004",
        name: "Charmander",
        classification: "Lizard Pokémon",
        fleeRate: 0.10,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    },
    {
        id: "UG9rZW1vbjowMDU=",
        number: "005",
        name: "Charmeleon",
        classification: "Flame Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
    },
    {
        id: "UG9rZW1vbjowMDY=",
        number: "006",
        name: "Charizard",
        classification: "Flame Pokémon",
        fleeRate: 0.05,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    },
    {
        id: "UG9rZW1vbjowMDc=",
        number: "007",
        name: "Squirtle",
        classification: "Tiny Turtle Pokémon",
        fleeRate: 0.10,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    },
    {
        id: "UG9rZW1vbjowMDg=",
        number: "008",
        name: "Wartortle",
        classification: "Turtle Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
    },
    {
        id: "UG9rZW1vbjowMDk=",
        number: "009",
        name: "Blastoise",
        classification: "Shellfish Pokémon",
        fleeRate: 0.05,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
    },
    {
        id: "UG9rZW1vbjowMTA=",
        number: "010",
        name: "Caterpie",
        classification: "Worm Pokémon",
        fleeRate: 0.20,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
    },
    {
        id: "UG9rZW1vbjowMTE=",
        number: "011",
        name: "Metapod",
        classification: "Cocoon Pokémon",
        fleeRate: 0.09,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png",
    },
    {
        id: "UG9rZW1vbjowMTI=",
        number: "012",
        name: "Butterfree",
        classification: "Butterfly Pokémon",
        fleeRate: 0.06,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png",
    },
    {
        id: "UG9rZW1vbjowMTM=",
        number: "013",
        name: "Weedle",
        classification: "Hairy Bug Pokémon",
        fleeRate: 0.20,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png",
    },
    {
        id: "UG9rZW1vbjowMTQ=",
        number: "014",
        name: "Kakuna",
        classification: "Cocoon Pokémon",
        fleeRate: 0.09,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png",
    },
    {
        id: "UG9rZW1vbjowMTU=",
        number: "015",
        name: "Beedrill",
        classification: "Poison Bee Pokémon",
        fleeRate: 0.06,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png",
    },
    {
        id: "UG9rZW1vbjowMTY=",
        number: "016",
        name: "Pidgey",
        classification: "Tiny Bird Pokémon",
        fleeRate: 0.20,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
    },
    {
        id: "UG9rZW1vbjowMTc=",
        number: "017",
        name: "Pidgeotto",
        classification: "Bird Pokémon",
        fleeRate: 0.09,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png",
    },
    {
        id: "UG9rZW1vbjowMTg=",
        number: "018",
        name: "Pidgeot",
        classification: "Bird Pokémon",
        fleeRate: 0.06,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png",
    },
    {
        id: "UG9rZW1vbjowMTk=",
        number: "019",
        name: "Rattata",
        classification: "Mouse Pokémon",
        fleeRate: 0.20,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png",
    },
    {
        id: "UG9rZW1vbjowMjA=",
        number: "020",
        name: "Raticate",
        classification: "Mouse Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png",
    },
    {
        id: "UG9rZW1vbjowMjE=",
        number: "021",
        name: "Spearow",
        classification: "Tiny Bird Pokémon",
        fleeRate: 0.15,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png",
    },
    {
        id: "UG9rZW1vbjowMjI=",
        number: "022",
        name: "Fearow",
        classification: "Beak Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png",
    },
    {
        id: "UG9rZW1vbjowMjM=",
        number: "023",
        name: "Ekans",
        classification: "Snake Pokémon",
        fleeRate: 0.15,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png",
    },
    {
        id: "UG9rZW1vbjowMjQ=",
        number: "024",
        name: "Arbok",
        classification: "Cobra Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png",
    },
    {
        id: "UG9rZW1vbjowMjU=",
        number: "025",
        name: "Pikachu",
        classification: "Mouse Pokémon",
        fleeRate: 0.10,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    },
    {
        id: "UG9rZW1vbjowMjY=",
        number: "026",
        name: "Raichu",
        classification: "Mouse Pokémon",
        fleeRate: 0.06,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
    },
    {
        id: "UG9rZW1vbjowMjc=",
        number: "027",
        name: "Sandshrew",
        classification: "Mouse Pokémon",
        fleeRate: 0.10,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
    },
    {
        id: "UG9rZW1vbjowMjg=",
        number: "028",
        name: "Sandslash",
        classification: "Mouse Pokémon",
        fleeRate: 0.06,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png",
    },
    {
        id: "UG9rZW1vbjowMjk=",
        number: "029",
        name: "Nidoran♀",
        classification: "Poison Pin Pokémon",
        fleeRate: 0.15,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png",
    },
    {
        id: "UG9rZW1vbjowMzA=",
        number: "030",
        name: "Nidorina",
        classification: "Poison Pin Pokémon",
        fleeRate: 0.07,
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png",
    }
];